[tool.pylint."MESSAGES CONTROL"]
disable = [
    "too-few-public-methods",
    "too-many-locals",
    "unused-argument",
    "too-many-arguments",
    "too-many-positional-arguments"
]
version = "0.1.1"
[tool.pylint.format]
max-line-length = 120
